import {chromium} from '@playwright/test';import assert from 'node:assert/strict';import {mkdir} from 'node:fs/promises';
import translations from '../src/data/translations.json' with {type:'json'};
const origin=process.env.TEST_ORIGIN||'http://127.0.0.1:4326';const browser=await chromium.launch({headless:true});const context=await browser.newContext({viewport:{width:1440,height:1000},colorScheme:'dark'});const page=await context.newPage();const errors=[];page.on('pageerror',e=>errors.push(e.message));
await mkdir('test-results',{recursive:true});
try{
  await context.addInitScript(()=>localStorage.setItem('techniques-theme','dark'));
  await page.goto(origin,{waitUntil:'networkidle'});assert.equal(await page.locator('html').getAttribute('data-theme'),'light');assert.equal(await page.locator('html').evaluate(el=>getComputedStyle(el).backgroundColor),'rgb(255, 255, 255)');await page.screenshot({path:'test-results/home-desktop.png',fullPage:true});assert.equal(await page.locator('h1').textContent(),'점성술 기법 백과');
  await page.getByRole('textbox',{name:'기법·용어 검색'}).fill('리셉션');await page.getByRole('button',{name:'검색',exact:true}).click();await page.waitForSelector('#results .result');assert.match(await page.locator('#results').textContent(),/리셉션/);
  await page.locator('#query').fill('행운점');await page.waitForTimeout(200);assert.match(await page.locator('#results').textContent(),/포르투나/);
  await page.locator('#query').fill('빛의전달');await page.waitForTimeout(200);await page.locator('#results a').first().click();await page.waitForURL('**/wiki/translation-of-light/');assert.equal(await page.locator('#references ol li').count(),2);
  const edition=await page.getByRole('link',{name:'고정 인용판',exact:true}).getAttribute('href');await page.goto(origin+edition);assert.match(await page.locator('.note').first().textContent(),/고정된 인용판/);assert.equal(await page.locator('meta[name=robots]').getAttribute('content'),'noindex,follow');
  await page.goto(origin+'/wiki/lot-of-fortune/');assert.match(await page.locator('output').textContent(),/160/);await page.locator('select[name=night]').selectOption('true');assert.match(await page.locator('output').textContent(),/40/);await page.screenshot({path:'test-results/article-desktop.png',fullPage:true});
  await page.goto(origin+'/wiki/annual-profections/');await page.locator('input[name=age]').fill('12');assert.match(await page.locator('output').textContent(),/^1하우스/);
  await page.goto(origin+'/glossary/?q=七政四餘');await page.waitForSelector('.term-table');assert.match(await page.locator('.term-table').textContent(),/칠정사여/);
  await page.locator('.term-table a').first().click();await page.waitForURL('**/topics/qizheng-siyu/');assert.match(await page.locator('.lead').textContent(),/해·달/);assert(await page.locator('#references a').count()>0);assert.equal(await page.locator('meta[name=robots]').count(),0);
  await page.goto(origin+'/glossary/');await page.waitForSelector('.term-table');await page.screenshot({path:'test-results/glossary-white.png',fullPage:false});
  await page.goto(origin+'/catalogue/?state=article');await page.waitForSelector('#count');assert.match(await page.locator('#count').textContent(),/31개 항목/);await page.locator('#query').fill('없는용어xyz');await page.waitForTimeout(200);assert.match(await page.locator('#results').textContent(),/일치하는 항목이 없습니다/);
  await page.goto(origin+'/compare/');assert.match(await page.locator('#left-panel h2').textContent(),/빛의 전달/);await page.locator('#right').selectOption('reception');assert.equal(await page.locator('#right-panel h2').textContent(),'리셉션');
  await page.goto(origin+'/search/');const search=page.locator('#fulltext-search input');await search.waitFor();await search.fill('리셉션');await page.waitForSelector('.pagefind-ui__result');assert(await page.locator('.pagefind-ui__result').count()>0);
  await page.goto(origin+'/translations/');assert.equal(await page.locator('main .source-item').count(),translations.length);
  await page.getByRole('link',{name:'주간성과 야간성',exact:true}).click();await page.waitForURL('**/translations/ptolemy-diurnal-nocturnal/');
  assert.equal(await page.locator('#translation p').count(),3);assert.match(await page.locator('#translation').textContent(),/토성의 차가움/);assert.match(await page.locator('#references a').first().getAttribute('href'),/ashmand.*#page=55/);
  await page.screenshot({path:'test-results/translation-desktop.png',fullPage:true});
  await page.goto(origin+'/topics/sect/');await page.getByRole('link',{name:'주간성과 야간성',exact:true}).click();assert.match(page.url(),/translations\/ptolemy-diurnal-nocturnal/);
  await page.goto(origin+'/translations/ptolemy-egyptian-chaldean-terms/');assert.equal(await page.locator('#egyptian-terms-table tbody tr').count(),12);assert.match(await page.locator('#egyptian-terms-table').textContent(),/금성 · 12° → 12°/);
  await page.locator('nav[aria-label="같은 문헌 이어 읽기"] a[rel=next]').click();await page.waitForURL('**/translations/ptolemy-terms-rule/');assert.equal(await page.locator('#ptolemy-terms-table tbody tr').count(),12);assert.match(await page.locator('figcaption').textContent(),/자동 계산용 단일 표로 사용하지 않는다/);
  await page.goto(origin+'/topics/proper-face/');await page.getByRole('link',{name:'고유한 페이스·전차·기쁨의 조건',exact:true}).click();assert.match(await page.locator('#translation').textContent(),/태양에 대해서는 옥시덴탈/);
  await page.goto(origin+'/translations/ptolemy-aspect-geometry/');assert.equal(await page.getByRole('img',{name:'반원을 둘과 셋으로 나누는 애스펙트 도식'}).count(),1);await page.screenshot({path:'test-results/aspect-geometry-desktop.png',fullPage:true});
  await page.goto(origin+'/search/');await page.locator('#fulltext-search input').fill('익절테이션과 폴의 배정');await page.waitForSelector('.pagefind-ui__result a[href*="/translations/ptolemy-exaltations/"]');
  await page.setViewportSize({width:390,height:844});await page.goto(origin);await page.getByRole('button',{name:'분류',exact:true}).click();assert.equal(await page.getByRole('button',{name:'분류',exact:true}).getAttribute('aria-expanded'),'true');await page.keyboard.press('Escape');assert.equal(await page.getByRole('button',{name:'분류',exact:true}).getAttribute('aria-expanded'),'false');await page.screenshot({path:'test-results/home-mobile.png',fullPage:true});
  for(const path of ['/wiki/reception/','/glossary/','/compare/','/catalogue/','/translations/','/translations/ptolemy-diurnal-nocturnal/','/translations/ptolemy-terms-rule/','/translations/ptolemy-aspect-geometry/']){await page.goto(origin+path);const overflow=await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth);assert.equal(overflow,false,`overflow at ${path}`);}
  await page.screenshot({path:'test-results/translation-mobile.png',fullPage:true});
  await page.goto(origin+'/wiki/reception/');await page.screenshot({path:'test-results/article-mobile.png',fullPage:true});await page.getByRole('button',{name:'색상 테마 전환'}).click();await page.screenshot({path:'test-results/article-dark.png',fullPage:true});assert.equal(await page.locator('html').getAttribute('data-theme'),'dark');await page.reload();assert.equal(await page.locator('html').getAttribute('data-theme'),'dark');await page.getByRole('button',{name:'색상 테마 전환'}).click();await page.reload();assert.equal(await page.locator('html').getAttribute('data-theme'),'light');
  const response=await page.goto(origin+'/not-a-real-document/');assert.equal(response.status(),404);
  assert.deepEqual(errors,[]);console.log('Browser checks passed: search, aliases, full text, citations, fixed edition, calculations, glossary, filters, comparison, mobile, theme, 404; no page errors.');
}finally{await browser.close();}
