import {chromium} from '@playwright/test';import assert from 'node:assert/strict';import {mkdir} from 'node:fs/promises';
import data from '../src/data/editorial/breiter-corrigenda.json' with {type:'json'};
import corpus from '../src/data/translations.json' with {type:'json'};
const origin=process.env.TEST_ORIGIN||'http://127.0.0.1:4326',browser=await chromium.launch({headless:true});
const page=await browser.newPage({viewport:{width:1440,height:1000}}),errors=[];page.on('pageerror',e=>errors.push(e.message));await mkdir('test-results',{recursive:true});
try{
 await page.goto(origin+'/translations/',{waitUntil:'networkidle'});assert.equal(await page.locator('#manilius-breiter1907 .source-item').count(),154);await page.locator('a[href="/editorial/breiter1907-corrigenda/"]').click();await page.waitForURL('**/editorial/breiter1907-corrigenda/');
 assert.match(await page.locator('h1').textContent(),/정오표 적용/);assert.equal(await page.locator('.erratum-application').count(),7);assert.equal(await page.locator('[data-layer="poem-body"]').count(),3);assert.equal(await page.locator('.korean-context').count(),25);assert.equal(await page.locator('.latin-verse').count(),128);assert.equal(await page.locator('.corrected-verse').count(),3);
 assert.match(await page.locator('[data-reading-scope]').textContent(),/중복 합산하지/);
 for(const d of data.items){const section=page.locator('#'+d.id);assert.equal(await section.locator('.target-before').textContent(),d.targetBefore);assert.equal(await section.locator('.target-after').textContent(),d.targetAfter);assert.deepEqual(await section.locator('.korean-context').allTextContents(),d.contextBlocks.map(b=>b.ko));assert.deepEqual(await section.locator('.latin-verse').allTextContents(),d.contextAfter.map(v=>v.text));assert.equal(await section.locator('.original-context-link').getAttribute('href'),d.originalLink);}
 await page.locator('#e04 .latin-reading summary').nth(2).click();await page.locator('#e04-p3').evaluate(el=>el.scrollIntoView({block:'start'}));assert.match(await page.locator('#e04-p3 .latin-verse').last().textContent(),/a libra/);await page.screenshot({path:'test-results/corrigenda-libra-desktop.png',fullPage:false});
 for(const d of data.items){await page.goto(origin+`/translations/${d.translationId}/`);const note=page.locator('[data-corrigenda-notice]');assert.equal(await note.count(),1);assert.equal(await note.locator('a').getAttribute('href'),`/editorial/breiter1907-corrigenda/#${d.id}`);const t=corpus.find(t=>t.id===d.translationId);assert.deepEqual(await page.locator('#translation > p').allTextContents(),t.paragraphs);if(d.layer==='poem-body')assert((await page.locator('.latin-verse').allTextContents()).includes(d.targetBefore));}
 await page.goto(origin+'/translations/ptolemy-proem/');assert.equal(await page.locator('[data-corrigenda-notice]').count(),0);
 await page.goto(origin+'/translations/manilius-ii-203-222/');await page.locator('[data-corrigenda-notice] a').click();await page.waitForURL('**/editorial/breiter1907-corrigenda/#e04');
 await page.goto(origin+'/editorial/breiter1907-preface/#corrigenda');await page.locator('a[href="/editorial/breiter1907-corrigenda/"]').click();await page.waitForURL('**/editorial/breiter1907-corrigenda/');
 await page.goto(origin+'/search/');await page.locator('#fulltext-search input').fill('Breiter 정오표 적용 대조판');await page.waitForSelector('.pagefind-ui__result a[href*="/editorial/breiter1907-corrigenda/"]');
 await page.goto(origin+'/editorial/breiter1907-corrigenda/');await page.locator('details').evaluateAll(xs=>xs.forEach(x=>x.open=true));
 for(const image of await page.locator('figure img').all()){await image.scrollIntoViewIfNeeded();await image.evaluate(e=>e.decode());assert(await image.evaluate(e=>e.naturalWidth>500));}
 for(const width of [390,320]){await page.setViewportSize({width,height:844});for(const d of data.items){await page.locator('#'+d.id).scrollIntoViewIfNeeded();assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false,`${width}px overflow ${d.id}`);}}
 await page.setViewportSize({width:390,height:844});await page.goto(origin+'/editorial/breiter1907-corrigenda/#e07');await page.locator('#e07 .latin-reading').nth(1).evaluate(el=>el.open=true);await page.locator('#e07 .corrected-verse').evaluate(el=>el.scrollIntoView({block:'center'}));await page.screenshot({path:'test-results/corrigenda-orbe-mobile.png',fullPage:false});
 await page.goto(origin+'/editorial/breiter1907-corrigenda/#e02');await page.locator('#e02').evaluate(el=>el.scrollIntoView({block:'start'}));await page.screenshot({path:'test-results/corrigenda-apparatus-mobile.png',fullPage:false});
 assert.deepEqual(errors,[]);console.log('Corrigenda browser checks passed: 7 located entries, 3 body/4 apparatus, 25 Korean paragraphs, 128 Latin lines, 3 changed lines, 7 preserved-reader notices, facsimiles, search and expanded 390px/320px layouts.');
}finally{await browser.close();}
